#!/usr/bin/env node
/**
 * Regenerate `src/locales/<lang>/index.ts` from the JSON files in that folder.
 *
 *   node scripts/i18n-barrels.mjs
 *
 * Each barrel imports every namespace and flattens it to one `namespace.key`
 * table, which is what `src/lib/i18n.tsx` consumes. Generated rather than
 * hand-written so adding a namespace cannot silently fail to load: the JSON
 * file on disk is the single source of truth for what a locale contains.
 *
 * `scripts/i18n-test.mjs` fails if a barrel is missing a namespace that exists
 * on disk, so a forgotten run of this script is caught in CI rather than at
 * runtime as a screen full of raw key names.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const LOCALES = join(ROOT, "src", "locales");
const LANGS = ["en", "ru", "uz"];

/** A valid JS identifier for the import binding, e.g. virtualPatient. */
const binding = (ns) => ns.replace(/[^a-zA-Z0-9_$]/g, "_");

let changed = 0;

for (const lang of LANGS) {
  const dir = join(LOCALES, lang);
  const namespaces = readdirSync(dir)
    .filter((file) => file.endsWith(".json"))
    .map((file) => file.replace(/\.json$/, ""))
    .sort();

  const source = `/* Generated by scripts/i18n-barrels.mjs — do not edit by hand.
 * Edit the JSON files in this directory instead. */

${namespaces.map((ns) => `import ${binding(ns)} from "./${ns}.json";`).join("\n")}

function prefix(ns: string, entries: Record<string, string>) {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(entries)) out[\`\${ns}.\${key}\`] = value;
  return out;
}

/** Flat \`namespace.key\` table for one locale. */
const table: Record<string, string> = {
${namespaces.map((ns) => `  ...prefix("${ns}", ${binding(ns)}),`).join("\n")}
};

export default table;
`;

  const path = join(dir, "index.ts");
  const before = (() => {
    try {
      return readFileSync(path, "utf8");
    } catch {
      return null;
    }
  })();

  if (before === source) {
    console.log(`  ${lang}  unchanged (${namespaces.length} namespaces)`);
    continue;
  }
  writeFileSync(path, source);
  changed += 1;
  console.log(`  ${lang}  written (${namespaces.length} namespaces)`);
}

console.log(
  changed ? `\n\x1b[1mOK\x1b[0m  ${changed} barrel(s) regenerated` : "\n\x1b[1mOK\x1b[0m  already current"
);
