/* Generated by scripts/i18n-barrels.mjs — do not edit by hand.
 * Edit the JSON files in this directory instead. */

import article from "./article.json";
import auth from "./auth.json";
import challenges from "./challenges.json";
import common from "./common.json";
import communities from "./communities.json";
import dashboard from "./dashboard.json";
import feed from "./feed.json";
import leaderboard from "./leaderboard.json";
import learn from "./learn.json";
import library from "./library.json";
import nav from "./nav.json";
import profile from "./profile.json";
import read from "./read.json";
import room from "./room.json";
import run from "./run.json";
import settings from "./settings.json";
import virtualPatient from "./virtualPatient.json";
import watch from "./watch.json";

function prefix(ns: string, entries: Record<string, string>) {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(entries)) out[`${ns}.${key}`] = value;
  return out;
}

/** Flat `namespace.key` table for one locale. */
const table: Record<string, string> = {
  ...prefix("article", article),
  ...prefix("auth", auth),
  ...prefix("challenges", challenges),
  ...prefix("common", common),
  ...prefix("communities", communities),
  ...prefix("dashboard", dashboard),
  ...prefix("feed", feed),
  ...prefix("leaderboard", leaderboard),
  ...prefix("learn", learn),
  ...prefix("library", library),
  ...prefix("nav", nav),
  ...prefix("profile", profile),
  ...prefix("read", read),
  ...prefix("room", room),
  ...prefix("run", run),
  ...prefix("settings", settings),
  ...prefix("virtualPatient", virtualPatient),
  ...prefix("watch", watch),
};

export default table;
